FROM python:3.11.6-slim-bookworm as base 

# Install poetry
RUN pip install pipx  
RUN python3 -m pipx ensurepath
RUN pipx install poetry
ENV PATH="/root/.local/bin:$PATH"

ENV POETRY_VIRTUALENVS_IN_PROJECT=true

FROM base as dependencies
WORKDIR /home/app
COPY pyproject.toml poetry.lock ./  
RUN poetry install --with local
RUN poetry install --with ui

FROM base as app
ENV PYTHONUNBUFFERED=1  
ENV PORT=8080
EXPOSE 8080
   
RUN mkdir local_data && chown $(id -u):$(id -g) local_data  
RUN mkdir models && chown $(id -u):$(id -g) models

COPY --from=dependencies /home/app/.venv /home/app/.venv 
COPY private_gpt/ private_gpt
COPY fern/ fern
COPY *.yaml *.md ./
COPY scripts/ scripts
   
ENV PYTHONPATH="$PYTHONPATH:/private_gpt/"
  
ENTRYPOINT python -m private_gpt
