version: "3.8"
services:

  private-gpt:
  
    build: 
      context: . # Set build context  
      dockerfile: Dockerfile.local
    ports:
      - 8001:8080  
    environment:
      PORT: 8080
      PGPT_PROFILES: docker  
      PGPT_MODE: local
